### ISSUE TITLE
How long does it take to train once

### ISSUE THREAD

**Issue by 23ds2** [osmanberke/Ensemble-of-DNNs#1]

**Comment by osmanberke** [comment]
On my computer (equipped with an NVIDIA GeForce GTX 1650 GPU), the first stage of training takes approximately 1 hour for the benchmark dataset with a signal length of 1 second. It takes slightly longer for the BETA dataset and less time for shorter signal lengths. The fine-tuning stage takes about 30 minutes, with an average fine-tuning time of 40 seconds per participant.
